### ISSUE TITLE
Safari 8: Requires page reload for tabs opened in background

### ISSUE THREAD

**Issue by bismark** [guyht/vimari#47]
Action: open a tab behind the current tab using shift+f or command clicking
Expected: vimari is functional in new tab
Actual: vimari does not function in the new tab until you reload the page

**Comment by iamaziz** [comment]
I am having the same problem, BUT it only happens when I open another local html page on a new tab of the same Safari window. That is:

**Status**: you have couple tabs opened and `vimari` is functioning fine.
**Action**: open another tab `file:///Users/name/Desktop/page.html` in a new tab.
**Expected**: vimari is functional in all current tabs. 
**Actual**: vimari does not function in any of all the current tabs (unless refreshed).

However, as long as I don't open any local html page on the same window, `vimari` is functioning perfectly :+1: 

hope this will help fix the bug, unfortunately I am not sure how to do so.

> I am running Safari 8.0.3 (10600.3.18) on Yosemite 10.10.2.
